
2024-02-12 12:32:40,837 INFO: Printing the data: {'username': 'doggo', 'email': 'dog@mail.com', 'password': 'Superuser1', 'last_name': 'woof', 'date_of_birth': '2011-01-15', 'first_name': 'woof'} [in users.py:51]
2024-02-12 12:32:40,837 INFO: Validation successful. Validated data: {'username': 'doggo', 'email': 'dog@mail.com', 'first_name': 'woof', 'last_name': 'woof', 'date_of_birth': datetime.date(2011, 1, 15), 'password': 'Superuser1'} [in users.py:56]
2024-02-12 12:32:40,936 INFO: Printing the new user: <User doggo> [in users.py:61]
2024-02-12 12:32:40,949 INFO: User added to db: <User doggo> [in users.py:63]
2024-02-12 12:33:11,027 INFO: Printing the data: {'username': 'doggo', 'password': 'Superuser1'} [in users.py:86]
2024-02-12 12:33:11,027 INFO: Validation successful. Validated data: {'username': 'doggo', 'password': 'Superuser1'} [in users.py:92]
2024-02-12 12:33:11,031 INFO: User found: doggo [in users.py:100]
2024-02-12 12:33:11,031 INFO: Attempting to validate password for user: doggo [in users.py:107]
2024-02-12 12:33:11,031 ERROR: Invalid credentials for user: doggo [in users.py:109]
2024-02-12 12:35:14,763 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:35:19,391 INFO: Printing the data: {'username': 'doggo', 'password': 'Superuser1'} [in users.py:87]
2024-02-12 12:35:19,391 INFO: Validation successful. Validated data: {'username': 'doggo', 'password': 'Superuser1'} [in users.py:93]
2024-02-12 12:35:19,498 INFO: User found: doggo [in users.py:101]
2024-02-12 12:35:19,498 INFO: Attempting to validate password for user: doggo [in users.py:108]
2024-02-12 12:35:19,498 ERROR: Invalid credentials for user: doggo [in users.py:110]
2024-02-12 12:41:46,714 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:42:03,489 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:42:12,904 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:42:52,448 INFO: Printing the data: {'username': 'kong', 'email': 'kong@mail.com', 'password': 'Superuser1'} [in users.py:51]
2024-02-12 12:42:52,448 ERROR: Exception on /api/users/register [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask_smorest/response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/routes/users.py", line 52, in post
    validated_data, error = hf.validate_data(user_schema, data)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/helpers/helper_functions.py", line 20, in validate_data
    return schema.load(data), None
           ^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'first_name': ['Missing data for required field.'], 'last_name': ['Missing data for required field.']}
2024-02-12 12:42:58,235 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:43:01,687 INFO: Printing the data: {'username': 'kong', 'email': 'kong@mail.com', 'password': 'Superuser1'} [in users.py:51]
2024-02-12 12:43:01,688 ERROR: Exception on /api/users/register [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/flask_smorest/response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/routes/users.py", line 52, in post
    validated_data, error = hf.validate_data(user_schema, data)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/helpers/helper_functions.py", line 20, in validate_data
    return schema.load(data), None
           ^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'first_name': ['Missing data for required field.'], 'last_name': ['Missing data for required field.']}
2024-02-12 12:43:58,960 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:44:05,054 INFO: Printing the data: {'username': 'kong', 'email': 'kong@mail.com', 'password': 'Superuser1'} [in users.py:51]
2024-02-12 12:44:05,054 INFO: Validation successful. Validated data: {'username': 'kong', 'email': 'kong@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-02-12 12:44:05,148 INFO: Printing the new user: <User kong> [in users.py:62]
2024-02-12 12:44:05,159 INFO: User added to db: <User kong> [in users.py:64]
2024-02-12 12:44:24,268 INFO: Printing the data: {'username': 'kong', 'password': 'Superuser1'} [in users.py:87]
2024-02-12 12:44:24,268 INFO: Validation successful. Validated data: {'username': 'kong', 'password': 'Superuser1'} [in users.py:93]
2024-02-12 12:44:24,271 INFO: User found: kong [in users.py:101]
2024-02-12 12:44:24,271 INFO: Attempting to validate password for user: kong [in users.py:108]
2024-02-12 12:44:24,271 ERROR: Invalid credentials for user: kong [in users.py:110]
2024-02-12 12:56:03,360 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:56:15,425 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:56:43,934 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-12 12:57:09,362 INFO: Printing the data: {'username': 'eminem', 'email': 'rapgod@mail.com', 'password': 'Superuser1'} [in users.py:51]
2024-02-12 12:57:09,364 INFO: Validation successful. Validated data: {'username': 'eminem', 'email': 'rapgod@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-02-12 12:57:09,545 INFO: Printing the new user: <User eminem> [in users.py:62]
2024-02-12 12:57:09,565 INFO: User added to db: <User eminem> [in users.py:64]
2024-02-12 12:57:22,400 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-12 12:57:22,401 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-02-12 12:57:22,403 INFO: User found: eminem [in users.py:101]
2024-02-12 12:57:22,403 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-12 12:57:22,477 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-12 12:57:22,478 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-13 11:12:22,712 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-17 09:12:06,528 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:06:41,051 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:08:41,749 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:09:08,041 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:09:18,306 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:16:00,487 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:18:39,081 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:18:54,301 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-19 13:18:54,302 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-02-19 13:18:54,330 INFO: User found: eminem [in users.py:101]
2024-02-19 13:18:54,330 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-19 13:18:54,413 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-19 13:18:54,414 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-19 13:24:04,083 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:24:42,277 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-19 13:24:42,278 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-02-19 13:24:42,307 INFO: User found: eminem [in users.py:101]
2024-02-19 13:24:42,308 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-19 13:24:42,395 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-19 13:24:42,396 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-19 13:29:11,665 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 13:59:55,355 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 14:00:08,303 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-19 14:00:08,303 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-02-19 14:00:08,347 INFO: User found: eminem [in users.py:101]
2024-02-19 14:00:08,347 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-19 14:00:08,435 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-19 14:00:08,436 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-19 17:34:42,984 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 18:46:03,810 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-19 18:57:44,745 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-20 08:35:06,699 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-20 08:44:24,143 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-20 21:48:38,769 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-20 21:48:59,904 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-20 21:48:59,905 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-02-20 21:48:59,944 INFO: User found: eminem [in users.py:101]
2024-02-20 21:48:59,944 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-20 21:49:00,038 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-20 21:49:00,039 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-26 09:11:02,805 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-26 09:11:20,973 ERROR: Exception on /api/users/login [POST] [in app.py:828]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py", line 1168, in _check_request_limit
    raise e
  File "/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py", line 1149, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py", line 1086, in __evaluate_limits
    if not method(lim.limit, *args, **kwargs):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/limits/strategies.py", line 138, in hit
    self.storage.incr(
  File "/usr/local/lib/python3.11/site-packages/limits/storage/redis.py", line 198, in incr
    return int(self.lua_incr_expire([key], [expiry, amount]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 5931, in __call__
    return client.evalsha(self.sha, len(keys), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 5307, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 5291, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1086, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
2024-02-26 09:12:11,083 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-26 09:12:25,736 ERROR: Exception on /api/users/login [POST] [in app.py:828]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
    raise err
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py", line 1168, in _check_request_limit
    raise e
  File "/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py", line 1149, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py", line 1086, in __evaluate_limits
    if not method(lim.limit, *args, **kwargs):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/limits/strategies.py", line 138, in hit
    self.storage.incr(
  File "/usr/local/lib/python3.11/site-packages/limits/storage/redis.py", line 198, in incr
    return int(self.lua_incr_expire([key], [expiry, amount]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 5931, in __call__
    return client.evalsha(self.sha, len(keys), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 5307, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 5291, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1086, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
2024-02-26 09:13:10,951 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-26 09:13:16,361 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-26 09:13:16,362 INFO: Validation successful. Validated data: {'password': 'Superuser1', 'username': 'eminem'} [in users.py:93]
2024-02-26 09:13:16,517 INFO: User found: eminem [in users.py:101]
2024-02-26 09:13:16,517 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-26 09:13:16,598 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-26 09:13:16,599 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-26 09:14:50,696 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-26 09:14:50,703 INFO: Validation successful. Validated data: {'password': 'Superuser1', 'username': 'eminem'} [in users.py:93]
2024-02-26 09:14:50,718 INFO: User found: eminem [in users.py:101]
2024-02-26 09:14:50,719 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-26 09:14:50,828 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-26 09:14:50,829 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-27 10:44:00,051 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-27 10:44:14,369 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-27 10:44:14,370 INFO: Validation successful. Validated data: {'password': 'Superuser1', 'username': 'eminem'} [in users.py:93]
2024-02-27 10:44:14,509 INFO: User found: eminem [in users.py:101]
2024-02-27 10:44:14,509 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-27 10:44:14,586 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-27 10:44:14,587 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-27 11:09:15,372 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-27 11:11:10,611 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-27 11:16:18,499 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-27 11:19:03,831 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-27 11:19:03,834 INFO: Validation successful. Validated data: {'password': 'Superuser1', 'username': 'eminem'} [in users.py:93]
2024-02-27 11:19:03,944 INFO: User found: eminem [in users.py:101]
2024-02-27 11:19:03,944 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-27 11:19:04,023 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-27 11:19:04,023 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-27 11:20:49,978 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-27 11:21:38,471 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-27 11:21:38,471 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-02-27 11:21:38,632 INFO: User found: eminem [in users.py:101]
2024-02-27 11:21:38,633 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-27 11:21:38,709 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-27 11:21:38,710 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-27 12:14:37,243 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-02-27 12:14:37,249 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-02-27 12:14:37,275 INFO: User found: eminem [in users.py:101]
2024-02-27 12:14:37,275 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-02-27 12:14:37,376 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-02-27 12:14:37,377 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-02-27 12:14:40,359 ERROR: Exception on /api/users/logout [POST] [in app.py:828]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/DonkeyCrew/backend/helpers/helper_permissions.py", line 24, in wrapper
    self.current_user = get_jwt_identity()
                        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_jwt_extended/utils.py", line 63, in get_jwt_identity
    return get_jwt().get(config.identity_claim_key, None)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_jwt_extended/utils.py", line 29, in get_jwt
    raise RuntimeError(
RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method
2024-02-27 12:19:53,094 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-02-28 10:57:00,539 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-01 09:19:55,747 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-01 09:21:43,155 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-01 09:24:01,954 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-02 20:05:01,446 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-06 14:31:42,087 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-06 14:40:22,604 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-06 14:40:48,247 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-06 14:56:24,121 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-06 14:56:59,009 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-06 14:57:32,595 ERROR: Exception on /api/users/login [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
    raise err
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_limiter/extension.py", line 1168, in _check_request_limit
    raise e
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_limiter/extension.py", line 1149, in _check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_limiter/extension.py", line 1086, in __evaluate_limits
    if not method(lim.limit, *args, **kwargs):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/limits/strategies.py", line 138, in hit
    self.storage.incr(
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/limits/storage/redis.py", line 198, in incr
    return int(self.lua_incr_expire([key], [expiry, amount]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 5931, in __call__
    return client.evalsha(self.sha, len(keys), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 5307, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 5291, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/connection.py", line 1086, in get_connection
    connection.connect()
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
2024-03-06 14:58:30,084 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-06 14:58:35,446 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-06 14:58:35,447 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-06 14:58:35,480 INFO: User found: eminem [in users.py:101]
2024-03-06 14:58:35,480 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-06 14:58:35,568 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-06 14:58:35,568 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 10:19:59,837 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 10:20:57,905 INFO: Printing the data: {'username': 'tommyboy', 'email': 'tommy@mail.com', 'password': 'Superuser1'} [in users.py:51]
2024-03-07 10:20:57,906 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'email': 'tommy@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-07 10:20:58,004 INFO: Printing the new user: <User tommyboy> [in users.py:62]
2024-03-07 10:20:58,035 INFO: User added to db: <User tommyboy> [in users.py:64]
2024-03-07 10:55:51,767 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 11:06:07,044 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 11:08:47,663 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 11:11:03,730 INFO: Printing the data: {'email': 'davey@mail.com', 'username': 'davey', 'password': 'Superuser1'} [in users.py:51]
2024-03-07 11:11:03,731 INFO: Validation successful. Validated data: {'username': 'davey', 'email': 'davey@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-07 11:11:03,853 INFO: Printing the new user: <User davey> [in users.py:62]
2024-03-07 11:11:03,871 INFO: User added to db: <User davey> [in users.py:64]
2024-03-07 11:26:18,176 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 11:31:13,054 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 11:31:13,055 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 11:31:13,107 INFO: User found: tommyboy [in users.py:101]
2024-03-07 11:31:13,107 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 11:31:13,194 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 11:31:13,195 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 11:51:34,390 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 11:51:44,908 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 11:51:44,909 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 11:51:44,967 INFO: User found: eminem [in users.py:101]
2024-03-07 11:51:44,967 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 11:51:45,051 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 11:51:45,051 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:01:33,136 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 13:01:40,665 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:01:40,665 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:01:40,716 INFO: User found: eminem [in users.py:101]
2024-03-07 13:01:40,716 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:01:40,840 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:01:40,840 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:03:41,240 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:03:41,241 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:03:41,243 INFO: User found: eminem [in users.py:101]
2024-03-07 13:03:41,243 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:03:41,365 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:03:41,365 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:04:45,924 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:04:45,924 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:04:45,926 INFO: User found: eminem [in users.py:101]
2024-03-07 13:04:45,926 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:04:46,037 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:04:46,038 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:06:23,157 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:06:23,158 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:06:23,163 INFO: User found: eminem [in users.py:101]
2024-03-07 13:06:23,163 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:06:23,273 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:06:23,274 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:07:27,729 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:07:27,730 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:07:27,732 INFO: User found: eminem [in users.py:101]
2024-03-07 13:07:27,732 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:07:27,856 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:07:27,856 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:12:08,122 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 13:12:16,157 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:12:16,158 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:12:16,217 INFO: User found: eminem [in users.py:101]
2024-03-07 13:12:16,217 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:12:16,320 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:12:16,321 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:43:54,769 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 13:44:37,173 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:44:37,174 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:44:37,248 INFO: User found: eminem [in users.py:101]
2024-03-07 13:44:37,248 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:44:37,361 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:44:37,362 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:48:03,527 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:48:03,528 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:48:03,531 INFO: User found: eminem [in users.py:101]
2024-03-07 13:48:03,531 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:48:03,639 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:48:03,639 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:56:18,630 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 13:56:35,148 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:56:35,149 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:56:35,200 INFO: User found: eminem [in users.py:101]
2024-03-07 13:56:35,200 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:56:35,284 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:56:35,284 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:57:11,851 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:57:11,852 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:57:11,857 INFO: User found: eminem [in users.py:101]
2024-03-07 13:57:11,857 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 13:57:11,959 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 13:57:11,959 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 13:57:55,864 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 13:57:55,865 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 13:57:55,870 INFO: User found: tommyboy [in users.py:101]
2024-03-07 13:57:55,870 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 13:57:55,976 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 13:57:55,977 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:19:27,533 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 14:20:00,944 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:20:00,946 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:20:00,996 INFO: User found: eminem [in users.py:101]
2024-03-07 14:20:00,996 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:20:01,080 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:20:01,081 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:20:32,971 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser'} [in users.py:87]
2024-03-07 14:20:32,972 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser'} [in users.py:93]
2024-03-07 14:20:32,974 INFO: User found: eminem [in users.py:101]
2024-03-07 14:20:32,974 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:20:33,058 ERROR: Invalid credentials for user: eminem [in users.py:110]
2024-03-07 14:21:06,241 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:21:06,243 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:21:06,247 INFO: User found: eminem [in users.py:101]
2024-03-07 14:21:06,247 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:21:06,354 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:21:06,355 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:24:31,238 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:24:31,240 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:24:31,244 INFO: User found: eminem [in users.py:101]
2024-03-07 14:24:31,244 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:24:31,345 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:24:31,345 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:27:03,466 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:27:03,467 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:27:03,471 INFO: User found: tommyboy [in users.py:101]
2024-03-07 14:27:03,471 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 14:27:03,573 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 14:27:03,574 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:29:04,919 INFO: Printing the data: {'username': 'eminem', 'password': 'Auperuser1'} [in users.py:87]
2024-03-07 14:29:04,920 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Auperuser1'} [in users.py:93]
2024-03-07 14:29:04,922 INFO: User found: eminem [in users.py:101]
2024-03-07 14:29:04,922 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:29:05,010 ERROR: Invalid credentials for user: eminem [in users.py:110]
2024-03-07 14:29:09,567 INFO: Printing the data: {'username': 'eminem', 'password': 'Auperuser1'} [in users.py:87]
2024-03-07 14:29:09,568 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Auperuser1'} [in users.py:93]
2024-03-07 14:29:09,572 INFO: User found: eminem [in users.py:101]
2024-03-07 14:29:09,572 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:29:09,680 ERROR: Invalid credentials for user: eminem [in users.py:110]
2024-03-07 14:29:16,795 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:29:16,796 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:29:16,800 INFO: User found: eminem [in users.py:101]
2024-03-07 14:29:16,800 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:29:16,911 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:29:16,912 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:30:44,693 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:30:44,694 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:30:44,697 INFO: User found: tommyboy [in users.py:101]
2024-03-07 14:30:44,697 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 14:30:44,797 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 14:30:44,798 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:31:48,294 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 14:32:07,510 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:32:07,511 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:32:07,568 INFO: User found: eminem [in users.py:101]
2024-03-07 14:32:07,569 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:32:07,653 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:32:07,653 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:34:59,981 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:34:59,982 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:34:59,985 INFO: User found: eminem [in users.py:101]
2024-03-07 14:34:59,985 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:35:00,079 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:35:00,080 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:35:56,890 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 14:36:09,782 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:36:09,783 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:36:09,837 INFO: User found: tommyboy [in users.py:101]
2024-03-07 14:36:09,837 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 14:36:09,921 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 14:36:09,922 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:39:57,938 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:39:57,939 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:39:57,947 INFO: User found: eminem [in users.py:101]
2024-03-07 14:39:57,948 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:39:58,063 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:39:58,063 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:41:06,194 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:41:06,195 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:41:06,199 INFO: User found: tommyboy [in users.py:101]
2024-03-07 14:41:06,200 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 14:41:06,305 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 14:41:06,305 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:41:07,054 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:41:07,054 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:41:07,059 INFO: User found: tommyboy [in users.py:101]
2024-03-07 14:41:07,060 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 14:41:07,172 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 14:41:07,173 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:41:43,934 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:41:43,935 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:41:43,938 INFO: User found: tommyboy [in users.py:101]
2024-03-07 14:41:43,938 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 14:41:44,041 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 14:41:44,041 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:42:13,456 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:42:13,457 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:42:13,461 INFO: User found: tommyboy [in users.py:101]
2024-03-07 14:42:13,461 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 14:42:13,571 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 14:42:13,572 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 14:43:23,416 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:43:23,416 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:43:23,420 INFO: User found: eminem [in users.py:101]
2024-03-07 14:43:23,421 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:43:23,527 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:43:23,527 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 14:45:01,233 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 14:45:01,234 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 14:45:01,237 INFO: User found: eminem [in users.py:101]
2024-03-07 14:45:01,237 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 14:45:01,343 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 14:45:01,344 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 15:55:05,322 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 15:55:36,379 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 15:55:36,380 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 15:55:36,470 INFO: User found: eminem [in users.py:101]
2024-03-07 15:55:36,470 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 15:55:36,577 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 15:55:36,578 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 16:00:07,681 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 16:03:05,674 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 16:03:05,675 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 16:03:05,763 INFO: User found: eminem [in users.py:101]
2024-03-07 16:03:05,763 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 16:03:05,944 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 16:03:05,945 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 16:05:39,727 INFO: Printing the data: {'username': 'eminem', 'password': 'Supersuer1'} [in users.py:87]
2024-03-07 16:05:39,727 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Supersuer1'} [in users.py:93]
2024-03-07 16:05:39,729 INFO: User found: eminem [in users.py:101]
2024-03-07 16:05:39,730 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 16:05:39,863 ERROR: Invalid credentials for user: eminem [in users.py:110]
2024-03-07 16:05:53,802 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 16:05:53,802 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 16:05:53,804 INFO: User found: eminem [in users.py:101]
2024-03-07 16:05:53,805 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 16:05:53,961 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 16:05:53,962 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 17:15:08,506 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 17:15:52,220 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:15:52,222 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:15:52,280 INFO: User found: eminem [in users.py:101]
2024-03-07 17:15:52,281 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 17:15:52,413 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 17:15:52,415 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 17:16:36,798 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 17:16:56,941 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:16:56,942 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:16:57,014 INFO: User found: tommyboy [in users.py:101]
2024-03-07 17:16:57,015 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 17:16:57,145 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 17:16:57,149 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 17:19:28,887 INFO: Printing the data: {'email': 'munchkin@mail.com', 'username': 'munchkin', 'password': 'Superuser1'} [in users.py:51]
2024-03-07 17:19:28,888 INFO: Validation successful. Validated data: {'username': 'munchkin', 'email': 'munchkin@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-07 17:19:28,996 INFO: Printing the new user: <User munchkin> [in users.py:62]
2024-03-07 17:19:29,010 ERROR: An error occurred: Data integrity violation. [in helper_functions.py:59]
2024-03-07 17:19:47,863 INFO: Printing the data: {'email': 'munchkin@mail.com', 'username': 'munchkin', 'password': 'Superuser1'} [in users.py:51]
2024-03-07 17:19:47,863 INFO: Validation successful. Validated data: {'username': 'munchkin', 'email': 'munchkin@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-07 17:19:47,975 INFO: Printing the new user: <User munchkin> [in users.py:62]
2024-03-07 17:19:47,978 ERROR: An error occurred: Data integrity violation. [in helper_functions.py:59]
2024-03-07 17:20:16,416 INFO: Printing the data: {'username': 'munchkin', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:20:16,417 INFO: Validation successful. Validated data: {'username': 'munchkin', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:20:16,421 INFO: User found: munchkin [in users.py:101]
2024-03-07 17:20:16,421 INFO: Attempting to validate password for user: munchkin [in users.py:108]
2024-03-07 17:20:16,421 ERROR: Invalid credentials for user: munchkin [in users.py:110]
2024-03-07 17:23:55,042 INFO: Printing the data: {'username': 'munchkin', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:23:55,043 INFO: Validation successful. Validated data: {'username': 'munchkin', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:23:55,045 INFO: User found: munchkin [in users.py:101]
2024-03-07 17:23:55,045 INFO: Attempting to validate password for user: munchkin [in users.py:108]
2024-03-07 17:23:55,046 ERROR: Invalid credentials for user: munchkin [in users.py:110]
2024-03-07 17:26:54,195 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 17:27:57,260 INFO: Printing the data: {'email': 'newuser@mail.com', 'username': 'NewUser', 'password': 'Superuser1'} [in users.py:51]
2024-03-07 17:27:57,261 INFO: Validation successful. Validated data: {'username': 'NewUser', 'email': 'newuser@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-07 17:27:57,410 INFO: Printing the new user: <User NewUser> [in users.py:62]
2024-03-07 17:27:57,432 INFO: User added to db: <User NewUser> [in users.py:64]
2024-03-07 17:28:13,288 INFO: Printing the data: {'username': 'NewUser', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:28:13,289 INFO: Validation successful. Validated data: {'username': 'NewUser', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:28:13,297 INFO: User found: NewUser [in users.py:101]
2024-03-07 17:28:13,297 INFO: Attempting to validate password for user: NewUser [in users.py:108]
2024-03-07 17:28:13,436 INFO: Login successful for user: NewUser. Generating access token... [in users.py:116]
2024-03-07 17:28:13,438 INFO: Printing the response: <Response 451 bytes [200 OK]> [in users.py:129]
2024-03-07 17:28:31,635 INFO: Printing the data: {'username': 'NewUser', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:28:31,636 INFO: Validation successful. Validated data: {'username': 'NewUser', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:28:31,640 INFO: User found: NewUser [in users.py:101]
2024-03-07 17:28:31,641 INFO: Attempting to validate password for user: NewUser [in users.py:108]
2024-03-07 17:28:31,749 INFO: Login successful for user: NewUser. Generating access token... [in users.py:116]
2024-03-07 17:28:31,749 INFO: Printing the response: <Response 451 bytes [200 OK]> [in users.py:129]
2024-03-07 17:34:49,676 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:34:49,677 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:34:49,679 INFO: User found: tommyboy [in users.py:101]
2024-03-07 17:34:49,679 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 17:34:49,802 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 17:34:49,802 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 17:36:51,299 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 17:36:51,300 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 17:36:51,303 INFO: User found: tommyboy [in users.py:101]
2024-03-07 17:36:51,303 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 17:36:51,417 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 17:36:51,418 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:20:23,241 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 20:20:56,651 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:20:56,652 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:20:56,707 INFO: User found: eminem [in users.py:101]
2024-03-07 20:20:56,708 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 20:20:56,822 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 20:20:56,823 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 20:23:40,699 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:23:40,699 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:23:40,702 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:23:40,702 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:23:40,809 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:23:40,809 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:25:01,203 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-07 20:25:16,332 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:25:16,333 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:25:16,402 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:25:16,402 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:25:16,514 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:25:16,516 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:27:28,211 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:27:28,212 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:27:28,215 INFO: User found: eminem [in users.py:101]
2024-03-07 20:27:28,215 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 20:27:28,357 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 20:27:28,357 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 20:32:41,270 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:32:41,271 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:32:41,273 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:32:41,273 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:32:41,396 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:32:41,397 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:34:47,639 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:34:47,640 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:34:47,642 INFO: User found: eminem [in users.py:101]
2024-03-07 20:34:47,642 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 20:34:47,738 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 20:34:47,738 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 20:37:48,850 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:37:48,850 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:37:48,852 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:37:48,852 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:37:48,958 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:37:48,959 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:44:02,516 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:44:02,516 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:44:02,519 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:44:02,519 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:44:02,656 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:44:02,657 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:46:36,308 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:46:36,309 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:46:36,311 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:46:36,311 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:46:36,435 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:46:36,435 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:53:01,746 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:53:01,748 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:53:01,757 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:53:01,757 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:53:01,860 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:53:01,861 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:53:43,670 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:53:43,671 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:53:43,674 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:53:43,674 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:53:43,796 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:53:43,797 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:55:09,334 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:55:09,335 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:55:09,336 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:55:09,337 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:55:09,468 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:55:09,468 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 20:57:37,153 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 20:57:37,154 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 20:57:37,155 INFO: User found: tommyboy [in users.py:101]
2024-03-07 20:57:37,156 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 20:57:37,283 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 20:57:37,284 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 21:01:17,086 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:01:17,088 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:01:17,091 INFO: User found: tommyboy [in users.py:101]
2024-03-07 21:01:17,092 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 21:01:17,221 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 21:01:17,222 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 21:02:22,315 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:02:22,315 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:02:22,317 INFO: User found: tommyboy [in users.py:101]
2024-03-07 21:02:22,318 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 21:02:22,433 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 21:02:22,433 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 21:05:37,228 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:05:37,229 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:05:37,233 INFO: User found: eminem [in users.py:101]
2024-03-07 21:05:37,234 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-07 21:05:37,346 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-07 21:05:37,347 INFO: Printing the response: <Response 450 bytes [200 OK]> [in users.py:129]
2024-03-07 21:07:39,559 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:07:39,560 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:07:39,561 INFO: User found: tommyboy [in users.py:101]
2024-03-07 21:07:39,562 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 21:07:39,674 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 21:07:39,675 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 21:09:19,073 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:09:19,074 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:09:19,075 INFO: User found: tommyboy [in users.py:101]
2024-03-07 21:09:19,076 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 21:09:19,183 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 21:09:19,184 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 21:11:15,077 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:11:15,077 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:11:15,079 INFO: User found: tommyboy [in users.py:101]
2024-03-07 21:11:15,079 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 21:11:15,243 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 21:11:15,244 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 21:14:23,578 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:14:23,578 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:14:23,580 INFO: User found: tommyboy [in users.py:101]
2024-03-07 21:14:23,580 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 21:14:23,686 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 21:14:23,687 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-07 21:18:56,449 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-07 21:18:56,450 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-07 21:18:56,452 INFO: User found: tommyboy [in users.py:101]
2024-03-07 21:18:56,452 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-07 21:18:56,590 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-07 21:18:56,590 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 08:47:45,141 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 08:48:08,684 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 08:48:08,685 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 08:48:08,714 INFO: User found: tommyboy [in users.py:101]
2024-03-08 08:48:08,714 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 08:48:08,791 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 08:48:08,792 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 08:48:58,495 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 08:48:58,496 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 08:48:58,500 INFO: User found: tommyboy [in users.py:101]
2024-03-08 08:48:58,501 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 08:48:58,602 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 08:48:58,602 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 09:02:31,236 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 09:02:31,237 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 09:02:31,241 INFO: User found: tommyboy [in users.py:101]
2024-03-08 09:02:31,241 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 09:02:31,336 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 09:02:31,336 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 09:04:25,622 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 09:04:25,622 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 09:04:25,625 INFO: User found: tommyboy [in users.py:101]
2024-03-08 09:04:25,625 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 09:04:25,722 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 09:04:25,722 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 09:05:09,854 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 09:05:09,855 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 09:05:09,858 INFO: User found: tommyboy [in users.py:101]
2024-03-08 09:05:09,858 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 09:05:09,954 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 09:05:09,954 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 09:06:02,081 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 09:06:02,081 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 09:06:02,084 INFO: User found: tommyboy [in users.py:101]
2024-03-08 09:06:02,084 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 09:06:02,180 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 09:06:02,181 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 09:12:00,685 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 09:12:00,685 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 09:12:00,688 INFO: User found: tommyboy [in users.py:101]
2024-03-08 09:12:00,688 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 09:12:00,783 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 09:12:00,783 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 09:12:55,558 INFO: Printing the data: {'username': 'tommybot', 'password': 'superuser1'} [in users.py:87]
2024-03-08 09:12:55,559 INFO: Validation successful. Validated data: {'username': 'tommybot', 'password': 'superuser1'} [in users.py:93]
2024-03-08 09:12:55,561 ERROR: User not found: tommybot [in users.py:103]
2024-03-08 09:13:09,185 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 09:13:09,186 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 09:13:09,189 INFO: User found: tommyboy [in users.py:101]
2024-03-08 09:13:09,190 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 09:13:09,289 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 09:13:09,290 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:02:29,516 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 10:03:03,610 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:03:03,611 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:03:03,663 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:03:03,663 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:03:03,749 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:03:03,749 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:03:27,002 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:03:27,003 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:03:27,008 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:03:27,008 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:03:27,113 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:03:27,113 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:04:01,704 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:04:01,704 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:04:01,709 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:04:01,709 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:04:01,816 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:04:01,816 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:04:46,874 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:04:46,875 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:04:46,877 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:04:46,877 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:04:46,947 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:04:46,948 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:05:06,464 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:05:06,465 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:05:06,468 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:05:06,469 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:05:06,573 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:05:06,573 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:05:29,685 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:05:29,687 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:05:29,691 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:05:29,691 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:05:29,797 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:05:29,797 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:06:11,931 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:06:11,932 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:06:11,934 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:06:11,934 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:06:12,025 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:06:12,026 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:07:44,228 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:07:44,229 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:07:44,233 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:07:44,233 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:07:44,336 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:07:44,337 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:09:42,648 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:09:42,649 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:09:42,653 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:09:42,654 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:09:42,757 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:09:42,758 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:10:25,008 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:10:25,009 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:10:25,012 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:10:25,013 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:10:25,117 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:10:25,118 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:11:50,112 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 10:11:56,024 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:11:56,025 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:11:56,086 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:11:56,086 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:11:56,172 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:11:56,172 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:13:09,482 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:13:09,483 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:13:09,488 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:13:09,488 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:13:09,592 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:13:09,593 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 10:54:19,001 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 10:54:47,003 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 10:54:47,005 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 10:54:47,067 INFO: User found: tommyboy [in users.py:101]
2024-03-08 10:54:47,067 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 10:54:47,158 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 10:54:47,158 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 11:26:03,620 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 11:57:36,285 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 11:57:36,287 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 11:57:36,391 INFO: User found: tommyboy [in users.py:101]
2024-03-08 11:57:36,391 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 11:57:36,512 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 11:57:36,514 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 12:06:40,968 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 12:07:51,180 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:07:51,181 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:07:51,233 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:07:51,234 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:07:51,333 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:07:51,334 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 12:16:33,788 INFO: Printing the data: {'username': 'tommyboy', 'password': 'superuser1'} [in users.py:87]
2024-03-08 12:16:33,790 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'superuser1'} [in users.py:93]
2024-03-08 12:16:33,802 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:16:33,802 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:16:33,902 ERROR: Invalid credentials for user: tommyboy [in users.py:110]
2024-03-08 12:16:36,981 INFO: Printing the data: {'username': 'tommyboy', 'password': 'superuser1'} [in users.py:87]
2024-03-08 12:16:36,982 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'superuser1'} [in users.py:93]
2024-03-08 12:16:36,987 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:16:36,987 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:16:37,099 ERROR: Invalid credentials for user: tommyboy [in users.py:110]
2024-03-08 12:16:45,331 INFO: Printing the data: {'username': 'tommyboy', 'password': 'superuser1'} [in users.py:87]
2024-03-08 12:16:45,332 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'superuser1'} [in users.py:93]
2024-03-08 12:16:45,337 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:16:45,337 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:16:45,448 ERROR: Invalid credentials for user: tommyboy [in users.py:110]
2024-03-08 12:16:56,949 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:16:56,949 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:16:56,953 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:16:56,954 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:16:57,064 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:16:57,065 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 12:18:10,414 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:18:10,415 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:18:10,420 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:18:10,420 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:18:10,527 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:18:10,527 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 12:18:57,403 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:18:57,404 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:18:57,408 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:18:57,409 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:18:57,515 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:18:57,515 INFO: Printing the response: <Response 453 bytes [200 OK]> [in users.py:129]
2024-03-08 12:21:23,015 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 12:21:37,777 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
