2024-03-20 10:14:09,141 ERROR: Exception on /api/blog/posts [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 65, in post
    new_post.generate_slug()
  File "/Users/chriswest/Desktop/ai_donkeys/backend/models/blogs.py", line 58, in generate_slug
    slug = re.sub(r"\W+", "-", slug)
           ^^
NameError: name 're' is not defined
2024-03-20 10:14:39,548 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 10:14:59,561 ERROR: Exception on /api/blog/posts [GET] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 40, in get
    return jsonify([post.serialize() for post in posts]), 200
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 40, in <listcomp>
    return jsonify([post.serialize() for post in posts]), 200
                    ^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'serialize'
2024-03-20 10:15:49,981 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 10:17:00,284 ERROR: Exception on /api/blog/posts [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 54, in post
    validated_data, errors = hf.validate_data(post_schema, data)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/helpers/helper_functions.py", line 20, in validate_data
    return schema.load(data), None
           ^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'categories': ['Not a valid list.']}
2024-03-20 10:17:43,901 ERROR: Exception on /api/blog/posts [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 54, in post
    validated_data, errors = hf.validate_data(post_schema, data)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/helpers/helper_functions.py", line 20, in validate_data
    return schema.load(data), None
           ^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'categories': ['Not a valid list.']}
2024-03-20 10:18:58,765 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 10:20:41,790 ERROR: Exception on /api/blog/posts/creating-a-wolrd-with-ai-and-blockchain [PUT] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 94, in put
    hf.update_db(post)
TypeError: update_db() takes 0 positional arguments but 1 was given
2024-03-20 10:21:22,620 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 10:26:51,901 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 12:20:20,655 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 12:20:48,754 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 12:21:02,516 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 12:35:02,114 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:35:02,116 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:35:02,174 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:35:02,175 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:35:02,265 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:35:02,266 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:36:30,375 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:36:30,376 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:36:30,379 INFO: User found: eminem [in users.py:101]
2024-03-20 12:36:30,379 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 12:36:30,488 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 12:36:30,488 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-20 12:40:50,336 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:40:50,338 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:40:50,341 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:40:50,342 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:40:50,451 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:40:50,452 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:42:36,733 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:42:36,735 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:42:36,738 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:42:36,739 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:42:36,848 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:42:36,849 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:43:13,229 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:43:13,229 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:43:13,232 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:43:13,232 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:43:13,333 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:43:13,333 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:44:55,245 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:44:55,248 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:44:55,259 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:44:55,259 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:44:55,357 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:44:55,358 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:45:39,295 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:45:39,296 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:45:39,299 INFO: User found: eminem [in users.py:101]
2024-03-20 12:45:39,299 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 12:45:39,407 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 12:45:39,408 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-20 12:48:40,413 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:48:40,414 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:48:40,418 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:48:40,418 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:48:40,524 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:48:40,525 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:49:01,284 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:49:01,285 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:49:01,288 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:49:01,289 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:49:01,394 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:49:01,394 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:49:24,939 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:49:24,940 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:49:24,944 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:49:24,945 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:49:25,051 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:49:25,052 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:49:54,234 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:49:54,234 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:49:54,238 INFO: User found: tommyboy [in users.py:101]
2024-03-20 12:49:54,238 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 12:49:54,348 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 12:49:54,348 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 12:53:19,747 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:53:19,748 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:53:19,750 INFO: User found: eminem [in users.py:101]
2024-03-20 12:53:19,750 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 12:53:19,823 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 12:53:19,823 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-20 12:55:39,763 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 12:55:39,765 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 12:55:39,775 INFO: User found: eminem [in users.py:101]
2024-03-20 12:55:39,775 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 12:55:39,871 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 12:55:39,873 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-20 14:07:02,692 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 14:08:56,693 INFO: Printing the data: {'email': 'don@mail.com', 'username': 'Don', 'password': 'Superuser1'} [in users.py:51]
2024-03-20 14:08:56,694 INFO: Validation successful. Validated data: {'username': 'Don', 'email': 'don@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-20 14:08:56,842 INFO: Printing the new user: <User Don> [in users.py:62]
2024-03-20 14:08:56,857 INFO: User added to db: <User Don> [in users.py:64]
2024-03-20 14:11:50,445 INFO: Printing the data: {'email': 'art@mail.com', 'username': 'Art', 'password': 'Superuser1'} [in users.py:51]
2024-03-20 14:11:50,450 INFO: Validation successful. Validated data: {'username': 'Art', 'email': 'art@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-20 14:11:50,558 INFO: Printing the new user: <User Art> [in users.py:62]
2024-03-20 14:11:50,566 ERROR: An error occurred: Data integrity violation. [in helper_functions.py:59]
2024-03-20 14:11:59,334 INFO: Printing the data: {'username': 'art', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 14:11:59,334 INFO: Validation successful. Validated data: {'username': 'art', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 14:11:59,344 ERROR: User not found: art [in users.py:103]
2024-03-20 14:12:21,503 INFO: Printing the data: {'username': 'Art', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 14:12:21,504 INFO: Validation successful. Validated data: {'username': 'Art', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 14:12:21,507 ERROR: User not found: Art [in users.py:103]
2024-03-20 14:12:36,400 INFO: Printing the data: {'username': 'Art', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 14:12:36,401 INFO: Validation successful. Validated data: {'username': 'Art', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 14:12:36,405 ERROR: User not found: Art [in users.py:103]
2024-03-20 14:12:45,862 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 14:14:18,815 INFO: Printing the data: {'username': 'Art', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 14:14:18,816 INFO: Validation successful. Validated data: {'username': 'Art', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 14:14:18,870 ERROR: User not found: Art [in users.py:103]
2024-03-20 14:14:35,148 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 14:14:35,149 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 14:14:35,154 INFO: User found: tommyboy [in users.py:101]
2024-03-20 14:14:35,155 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 14:14:35,275 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 14:14:35,276 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 14:16:28,139 INFO: Printing the data: {'email': 'alice@mail.com', 'username': 'alice', 'password': 'Superuser1'} [in users.py:51]
2024-03-20 14:16:28,139 INFO: Validation successful. Validated data: {'username': 'alice', 'email': 'alice@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-20 14:16:28,220 INFO: Printing the new user: <User alice> [in users.py:62]
2024-03-20 14:16:28,230 INFO: User added to db: <User alice> [in users.py:64]
2024-03-20 14:16:43,623 INFO: Printing the data: {'username': 'alice', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 14:16:43,623 INFO: Validation successful. Validated data: {'username': 'alice', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 14:16:43,626 INFO: User found: alice [in users.py:101]
2024-03-20 14:16:43,627 INFO: Attempting to validate password for user: alice [in users.py:108]
2024-03-20 14:16:43,748 INFO: Login successful for user: alice. Generating access token... [in users.py:116]
2024-03-20 14:16:43,749 INFO: Printing the response: <Response 482 bytes [200 OK]> [in users.py:129]
2024-03-21 09:10:29,529 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-21 09:11:04,557 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-21 09:12:13,235 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:12:13,236 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:12:13,289 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:12:13,290 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:12:13,381 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:12:13,382 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:12:32,562 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:12:32,563 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:12:32,567 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:12:32,568 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:12:32,681 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:12:32,682 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:15:11,198 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:15:11,199 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:15:11,203 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:15:11,203 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:15:11,312 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:15:11,313 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:17:54,462 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:17:54,462 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:17:54,465 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:17:54,465 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:17:54,558 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:17:54,559 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:18:28,060 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:18:28,061 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:18:28,064 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:18:28,064 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:18:28,169 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:18:28,170 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:24:48,106 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:24:48,108 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:24:48,111 INFO: User found: eminem [in users.py:101]
2024-03-21 09:24:48,112 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-21 09:24:48,220 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-21 09:24:48,221 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-21 09:40:31,763 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:40:31,765 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:40:31,776 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:40:31,776 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:40:31,884 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:40:31,886 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:41:57,510 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:41:57,511 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:41:57,515 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:41:57,515 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:41:57,622 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:41:57,623 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:42:32,687 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:42:32,687 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:42:32,690 INFO: User found: tommyboy [in users.py:101]
2024-03-21 09:42:32,691 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 09:42:32,798 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 09:42:32,799 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 09:43:08,752 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 09:43:08,753 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 09:43:08,756 INFO: User found: eminem [in users.py:101]
2024-03-21 09:43:08,757 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-21 09:43:08,863 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-21 09:43:08,864 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-21 09:45:48,154 INFO: Printing the data: {'email': 'jon@mail.com', 'username': 'jon', 'password': 'password'} [in users.py:51]
2024-03-21 09:45:48,155 INFO: Validation successful. Validated data: {'username': 'jon', 'email': 'jon@mail.com', 'password': 'password'} [in users.py:57]
2024-03-21 09:45:48,272 INFO: Printing the new user: <User jon> [in users.py:62]
2024-03-21 09:45:48,290 INFO: User added to db: <User jon> [in users.py:64]
2024-03-21 09:46:00,864 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 09:46:00,865 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 09:46:00,868 INFO: User found: jon [in users.py:101]
2024-03-21 09:46:00,869 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 09:46:00,982 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 09:46:00,983 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:13:15,567 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:13:15,569 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:13:15,577 INFO: User found: jon [in users.py:101]
2024-03-21 10:13:15,577 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:13:15,669 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:13:15,670 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:14:11,261 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:14:11,262 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:14:11,264 INFO: User found: jon [in users.py:101]
2024-03-21 10:14:11,264 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:14:11,375 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:14:11,375 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:35:19,070 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:35:19,074 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:35:19,085 INFO: User found: jon [in users.py:101]
2024-03-21 10:35:19,085 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:35:19,191 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:35:19,193 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:44:32,348 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:44:32,348 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:44:32,354 INFO: User found: jon [in users.py:101]
2024-03-21 10:44:32,354 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:44:32,459 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:44:32,460 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:47:36,504 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:47:36,505 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:47:36,508 INFO: User found: jon [in users.py:101]
2024-03-21 10:47:36,508 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:47:36,613 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:47:36,614 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:49:22,782 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:49:22,784 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:49:22,787 INFO: User found: jon [in users.py:101]
2024-03-21 10:49:22,788 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:49:22,895 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:49:22,896 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:54:13,871 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:54:13,872 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:54:13,875 INFO: User found: jon [in users.py:101]
2024-03-21 10:54:13,875 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:54:13,982 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:54:13,982 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:54:46,496 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:54:46,497 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:54:46,498 INFO: User found: jon [in users.py:101]
2024-03-21 10:54:46,498 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:54:46,576 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:54:46,577 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 10:57:53,377 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-21 10:57:53,378 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-21 10:57:53,383 INFO: User found: tommyboy [in users.py:101]
2024-03-21 10:57:53,384 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-21 10:57:53,492 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-21 10:57:53,493 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-21 10:58:41,553 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 10:58:41,556 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 10:58:41,560 INFO: User found: jon [in users.py:101]
2024-03-21 10:58:41,560 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 10:58:41,665 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 10:58:41,666 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 11:12:29,789 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 11:12:29,792 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 11:12:29,796 INFO: User found: jon [in users.py:101]
2024-03-21 11:12:29,796 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 11:12:29,894 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 11:12:29,894 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-21 11:42:28,491 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-21 11:42:28,494 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-21 11:42:28,504 INFO: User found: jon [in users.py:101]
2024-03-21 11:42:28,504 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-21 11:42:28,618 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-21 11:42:28,620 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 10:59:09,596 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-22 11:00:07,687 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-22 11:00:39,555 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:00:39,556 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:00:39,605 INFO: User found: jon [in users.py:101]
2024-03-22 11:00:39,605 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:00:39,690 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:00:39,690 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:01:33,698 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:01:33,699 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:01:33,702 INFO: User found: jon [in users.py:101]
2024-03-22 11:01:33,702 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:01:33,803 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:01:33,804 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:03:30,870 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:03:30,871 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:03:30,875 INFO: User found: jon [in users.py:101]
2024-03-22 11:03:30,875 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:03:30,976 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:03:30,977 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:06:14,639 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:06:14,639 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:06:14,641 INFO: User found: jon [in users.py:101]
2024-03-22 11:06:14,641 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:06:14,734 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:06:14,734 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:12:03,108 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:12:03,109 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:12:03,113 INFO: User found: jon [in users.py:101]
2024-03-22 11:12:03,113 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:12:03,211 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:12:03,212 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:13:49,199 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:13:49,201 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:13:49,204 INFO: User found: jon [in users.py:101]
2024-03-22 11:13:49,205 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:13:49,305 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:13:49,305 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:15:10,556 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:15:10,556 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:15:10,557 INFO: User found: jon [in users.py:101]
2024-03-22 11:15:10,557 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:15:10,634 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:15:10,634 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:17:20,155 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:17:20,157 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:17:20,164 INFO: User found: jon [in users.py:101]
2024-03-22 11:17:20,164 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:17:20,273 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:17:20,274 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:18:40,954 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:18:40,955 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:18:40,958 INFO: User found: jon [in users.py:101]
2024-03-22 11:18:40,958 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:18:41,061 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:18:41,062 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:34:06,218 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:34:06,219 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:34:06,222 INFO: User found: jon [in users.py:101]
2024-03-22 11:34:06,222 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:34:06,337 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:34:06,337 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:35:07,888 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:35:07,888 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:35:07,890 INFO: User found: jon [in users.py:101]
2024-03-22 11:35:07,890 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:35:07,963 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:35:07,964 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:36:27,542 INFO: Printing the data: {'username': 'jon', 'password': 'paaword'} [in users.py:87]
2024-03-22 11:36:27,543 ERROR: Exception on /api/users/login [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/users.py", line 89, in post
    validated_data, error = hf.validate_data(user_login_schema, data)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/helpers/helper_functions.py", line 20, in validate_data
    return schema.load(data), None
           ^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'password': ['Shorter than minimum length 8.']}
2024-03-22 11:36:32,299 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:36:32,300 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:36:32,304 INFO: User found: jon [in users.py:101]
2024-03-22 11:36:32,305 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:36:32,417 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:36:32,417 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 11:44:31,617 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 11:44:31,619 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 11:44:31,629 INFO: User found: jon [in users.py:101]
2024-03-22 11:44:31,629 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 11:44:31,728 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 11:44:31,729 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 12:48:43,696 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-22 12:49:03,995 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 12:49:03,996 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 12:49:04,048 INFO: User found: jon [in users.py:101]
2024-03-22 12:49:04,048 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 12:49:04,141 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 12:49:04,142 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 12:54:39,939 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 12:54:39,939 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 12:54:39,943 INFO: User found: jon [in users.py:101]
2024-03-22 12:54:39,943 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 12:54:40,044 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 12:54:40,045 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 12:55:43,463 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 12:55:43,464 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 12:55:43,467 INFO: User found: jon [in users.py:101]
2024-03-22 12:55:43,468 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 12:55:43,573 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 12:55:43,573 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 12:56:13,405 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 12:56:13,405 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 12:56:13,409 INFO: User found: jon [in users.py:101]
2024-03-22 12:56:13,409 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 12:56:13,515 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 12:56:13,515 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 12:57:24,150 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 12:57:24,151 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 12:57:24,153 INFO: User found: jon [in users.py:101]
2024-03-22 12:57:24,153 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 12:57:24,229 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 12:57:24,230 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 12:58:04,300 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 12:58:04,301 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 12:58:04,304 INFO: User found: jon [in users.py:101]
2024-03-22 12:58:04,305 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 12:58:04,415 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 12:58:04,416 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 13:07:24,944 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 13:07:24,945 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 13:07:24,953 INFO: User found: jon [in users.py:101]
2024-03-22 13:07:24,954 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 13:07:25,040 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 13:07:25,041 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 13:08:56,461 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-22 13:08:56,462 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-22 13:08:56,465 INFO: User found: tommyboy [in users.py:101]
2024-03-22 13:08:56,465 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-22 13:08:56,568 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-22 13:08:56,569 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-22 13:20:39,089 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 13:20:39,091 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 13:20:39,099 INFO: User found: jon [in users.py:101]
2024-03-22 13:20:39,099 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 13:20:39,183 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 13:20:39,184 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 13:24:00,370 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 13:24:00,371 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 13:24:00,374 INFO: User found: jon [in users.py:101]
2024-03-22 13:24:00,374 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 13:24:00,475 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 13:24:00,476 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 13:24:19,221 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 13:24:19,222 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 13:24:19,227 INFO: User found: jon [in users.py:101]
2024-03-22 13:24:19,227 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 13:24:19,314 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 13:24:19,314 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 13:28:06,744 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 13:28:06,745 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 13:28:06,747 INFO: User found: jon [in users.py:101]
2024-03-22 13:28:06,747 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 13:28:06,858 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 13:28:06,859 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 13:31:50,912 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 13:31:50,913 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 13:31:50,917 INFO: User found: jon [in users.py:101]
2024-03-22 13:31:50,918 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 13:31:51,027 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 13:31:51,028 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-22 13:42:59,924 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-22 13:42:59,925 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-22 13:42:59,927 INFO: User found: jon [in users.py:101]
2024-03-22 13:42:59,928 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-22 13:43:00,015 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-22 13:43:00,016 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-25 09:47:18,490 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-25 15:53:59,771 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-25 15:54:14,608 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-25 15:54:14,609 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-25 15:54:14,648 INFO: User found: eminem [in users.py:101]
2024-03-25 15:54:14,648 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-25 15:54:14,732 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-25 15:54:14,733 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-26 08:40:31,647 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-26 08:43:22,698 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-26 08:43:34,396 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-26 08:43:34,396 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-26 08:43:34,430 INFO: User found: eminem [in users.py:101]
2024-03-26 08:43:34,430 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-26 08:43:34,510 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-26 08:43:34,511 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-26 08:57:15,538 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-26 08:57:15,541 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-26 08:57:15,552 INFO: User found: eminem [in users.py:101]
2024-03-26 08:57:15,553 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-26 08:57:15,646 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-26 08:57:15,647 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-26 09:07:41,676 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-26 09:08:15,804 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-26 09:08:46,501 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-26 09:09:01,915 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-26 09:09:01,916 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-26 09:09:01,981 INFO: User found: jon [in users.py:101]
2024-03-26 09:09:01,981 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-26 09:09:02,091 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-26 09:09:02,093 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-26 09:12:33,827 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-26 09:12:33,834 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-26 09:12:33,840 INFO: User found: jon [in users.py:101]
2024-03-26 09:12:33,840 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-26 09:12:33,959 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-26 09:12:33,960 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-26 09:12:47,229 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-26 09:12:47,231 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-26 09:12:47,235 INFO: User found: jon [in users.py:101]
2024-03-26 09:12:47,236 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-26 09:12:47,347 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-26 09:12:47,348 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-26 09:19:12,074 INFO: Printing the data: {'username': 'jon', 'password': 'password'} [in users.py:87]
2024-03-26 09:19:12,075 INFO: Validation successful. Validated data: {'username': 'jon', 'password': 'password'} [in users.py:93]
2024-03-26 09:19:12,079 INFO: User found: jon [in users.py:101]
2024-03-26 09:19:12,080 INFO: Attempting to validate password for user: jon [in users.py:108]
2024-03-26 09:19:12,190 INFO: Login successful for user: jon. Generating access token... [in users.py:116]
2024-03-26 09:19:12,191 INFO: Printing the response: <Response 477 bytes [200 OK]> [in users.py:129]
2024-03-26 09:23:10,887 INFO: Printing the data: {'username': 'fool', 'email': 'fool@mail.com', 'first_name': 'fool', 'last_name': 'you', 'date_of_birth': '1852-10-11', 'password': 'password'} [in users.py:51]
2024-03-26 09:23:10,892 INFO: Validation successful. Validated data: {'username': 'fool', 'email': 'fool@mail.com', 'first_name': 'fool', 'last_name': 'you', 'date_of_birth': datetime.date(1852, 10, 11), 'password': 'password'} [in users.py:57]
2024-03-26 09:23:11,000 INFO: Printing the new user: <User fool> [in users.py:62]
2024-03-26 09:23:11,014 INFO: User added to db: <User fool> [in users.py:64]
2024-03-26 09:23:21,572 INFO: Printing the data: {'username': 'fool', 'password': 'password'} [in users.py:87]
2024-03-26 09:23:21,573 INFO: Validation successful. Validated data: {'username': 'fool', 'password': 'password'} [in users.py:93]
2024-03-26 09:23:21,574 INFO: User found: fool [in users.py:101]
2024-03-26 09:23:21,575 INFO: Attempting to validate password for user: fool [in users.py:108]
2024-03-26 09:23:21,661 INFO: Login successful for user: fool. Generating access token... [in users.py:116]
2024-03-26 09:23:21,661 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-26 09:25:37,934 ERROR: Exception on /api/users/logout [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/helpers/helper_permissions.py", line 24, in wrapper
    self.current_user = get_jwt_identity()
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_jwt_extended/utils.py", line 63, in get_jwt_identity
    return get_jwt().get(config.identity_claim_key, None)
           ^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_jwt_extended/utils.py", line 29, in get_jwt
    raise RuntimeError(
RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method
2024-03-26 09:45:49,232 INFO: Printing the data: {'username': 'fool', 'password': 'password'} [in users.py:87]
2024-03-26 09:45:49,234 INFO: Validation successful. Validated data: {'username': 'fool', 'password': 'password'} [in users.py:93]
2024-03-26 09:45:49,242 INFO: User found: fool [in users.py:101]
2024-03-26 09:45:49,243 INFO: Attempting to validate password for user: fool [in users.py:108]
2024-03-26 09:45:49,333 INFO: Login successful for user: fool. Generating access token... [in users.py:116]
2024-03-26 09:45:49,334 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
